#include "pebble.h"

#if PBL_PLATFORM_EMERY
#define DISPLAY_WIDTH 200
#define DISPLAY_HEIGHT 228
#define DISPLAY_CENTER_X DISPLAY_WIDTH / 2
#define DISPLAY_CENTER_Y DISPLAY_HEIGHT / 2
#define DISPLAY_SCALE_X 1.39
#define DISPLAY_SCALE_Y 1.36
#elif PBL_PLATFORM_CHALK
#define DISPLAY_WIDTH 180
#define DISPLAY_HEIGHT 180
#define DISPLAY_CENTER_X DISPLAY_WIDTH / 2
#define DISPLAY_CENTER_Y DISPLAY_HEIGHT / 2
#define DISPLAY_SCALE_X 1.25
#define DISPLAY_SCALE_Y 1.07
#else
#define DISPLAY_WIDTH 144
#define DISPLAY_HEIGHT 168
#define DISPLAY_CENTER_X DISPLAY_WIDTH / 2
#define DISPLAY_CENTER_Y DISPLAY_HEIGHT / 2
#define DISPLAY_SCALE_X 1
#define DISPLAY_SCALE_Y 1
#endif